import { StaffRole } from "@prisma/client";
import type {
  OperationalAttentionItem,
  OperationalAttentionResolverContext,
} from "./types";

export const ATTENTION_FIXTURE_NOW = new Date("2026-06-27T00:00:00.000Z");

export const attentionResolverContextFixture: OperationalAttentionResolverContext = {
  organizationId: "org-1",
  role: StaffRole.OFFICE,
  userId: "user-1",
  now: ATTENTION_FIXTURE_NOW,
  mode: "workstation",
};

export const quoteActivationAttentionFixture: OperationalAttentionItem = {
  id: "quote_activation:quote-1",
  kind: "quote_activation",
  severity: "critical",
  ownerRoles: [StaffRole.OWNER, StaffRole.ADMIN, StaffRole.OFFICE],
  sourceType: "Quote",
  sourceId: "quote-1",
  quoteId: "quote-1",
  customerId: "customer-1",
  title: "Kitchen remodel",
  reason: "Approved quote is waiting for job setup.",
  safeNextAction: {
    label: "Activate job",
    href: "/quotes/quote-1/execution-review",
    actionKind: "ACTIVATE_JOB",
  },
  visibility: { canRead: true, canAct: true },
  updatedAt: new Date("2026-06-26T18:00:00.000Z"),
  rank: {
    priority: "critical",
    group: "investigate",
    lens: "attention",
    lane: "critical",
    withinLaneRank: 10,
  },
  workstationCompat: {
    workstationKind: "quote",
    filterCategory: "quotes",
    status: "Approved - ready to activate",
    nextStep: "Activate job",
    subtitle: "Quote: Kitchen remodel",
    typeLabel: "Quote",
    parentRecordId: "customer-1",
    parentLabel: "Cody Homeowner",
    href: "/quotes/quote-1/execution-review",
    workflow: {
      statusLabel: "Approved - ready to activate",
      priority: "critical",
      requiredItems: [],
      optionalItems: [],
      satisfiedItems: ["Execution plan is ready - you can activate the job."],
      nextAction: {
        type: "ACTIVATE_JOB",
        label: "Activate job",
        description: "Commercial terms are approved and the work plan is ready.",
        surface: "full-record",
        href: "/quotes/quote-1/execution-review",
      },
      secondaryActions: [],
      canCompleteInWorkstation: false,
      reason: "Commercial terms are approved and the work plan is ready.",
    },
  },
};

export const changeOrderSendAttentionFixture: OperationalAttentionItem = {
  id: "change_order_send:co-1",
  kind: "change_order_send",
  severity: "blocking",
  ownerRoles: [StaffRole.OWNER, StaffRole.ADMIN, StaffRole.OFFICE],
  sourceType: "ChangeOrder",
  sourceId: "co-1",
  changeOrderId: "co-1",
  jobId: "job-1",
  title: "CO-001 - Add backsplash",
  reason: "This Change Order changes price only. Confirm it does not change the work plan before sending.",
  safeNextAction: {
    label: "Mark as price-only",
    href: "/jobs/job-1/change-orders?focus=co-1",
    actionKind: "CONFIRM_NO_WORK_IMPACT",
    disabledReason: "Confirm no work impact before sending.",
  },
  visibility: { canRead: true, canAct: true },
  updatedAt: new Date("2026-06-26T17:00:00.000Z"),
  rank: {
    priority: "high",
    group: "waiting",
    lens: "waiting",
    lane: "upcoming",
    withinLaneRank: 20,
  },
  workstationCompat: {
    workstationKind: "change-order",
    filterCategory: "quotes",
    status: "Change Order DRAFT",
    nextStep: "Mark as price-only",
    subtitle: "Kitchen remodel",
    typeLabel: "Change Order",
    parentRecordId: "job-1",
    href: "/jobs/job-1/change-orders?focus=co-1",
  },
};

export const changeOrderApplyAttentionFixture: OperationalAttentionItem = {
  id: "change_order_apply:co-2",
  kind: "change_order_apply",
  severity: "critical",
  ownerRoles: [StaffRole.OWNER, StaffRole.ADMIN, StaffRole.OFFICE],
  sourceType: "ChangeOrder",
  sourceId: "co-2",
  changeOrderId: "co-2",
  jobId: "job-1",
  title: "CO-002 - Add cabinet repair",
  reason: "Accepted Change Order is waiting to be applied to the job.",
  safeNextAction: {
    label: "Apply accepted Change Order",
    href: "/jobs/job-1/change-orders?focus=co-2",
    actionKind: "APPLY_CHANGE_ORDER",
  },
  visibility: { canRead: true, canAct: true },
  updatedAt: new Date("2026-06-26T16:00:00.000Z"),
  rank: {
    priority: "critical",
    group: "ready",
    lens: "attention",
    lane: "critical",
    withinLaneRank: 30,
  },
  workstationCompat: {
    workstationKind: "change-order",
    filterCategory: "quotes",
    status: "Change Order ACCEPTED",
    nextStep: "Apply accepted Change Order.",
    subtitle: "Kitchen remodel",
    typeLabel: "Change Order",
    parentRecordId: "job-1",
    href: "/jobs/job-1/change-orders?focus=co-2",
  },
};

export const taskProofAttentionFixture: OperationalAttentionItem = {
  id: "proof_required:task-1",
  kind: "proof_required",
  severity: "blocking",
  ownerRoles: [StaffRole.OWNER, StaffRole.ADMIN, StaffRole.OFFICE, StaffRole.FIELD],
  sourceType: "Task",
  sourceId: "task-1",
  taskId: "task-1",
  jobId: "job-1",
  title: "Install cabinets",
  reason: "Task needs completion proof.",
  safeNextAction: {
    label: "Complete the task",
    href: "/jobs/job-1",
    actionKind: "COMPLETE_TASK",
  },
  visibility: { canRead: true, canAct: true },
  updatedAt: new Date("2026-06-26T15:00:00.000Z"),
  rank: {
    priority: "medium",
    group: "active",
    lens: "attention",
    lane: "due",
    withinLaneRank: 40,
  },
  workstationCompat: {
    workstationKind: "task",
    filterCategory: "tasks",
    status: "Needs proof",
    nextStep: "Complete the task.",
    subtitle: "Cabinet install",
    parentRecordId: "job-1",
    href: "/jobs/job-1",
    dueAt: new Date("2026-06-27T23:59:59.000Z"),
  },
};

export const paymentReviewAttentionFixture: OperationalAttentionItem = {
  id: "payment_review:payment-1",
  kind: "payment_review",
  severity: "attention",
  ownerRoles: [StaffRole.OWNER, StaffRole.ADMIN, StaffRole.OFFICE],
  sourceType: "Payment",
  sourceId: "payment-1",
  jobId: "job-1",
  title: "Deposit",
  reason: "Payment is due.",
  safeNextAction: {
    label: "Record payment or waive requirement.",
    href: "/jobs/job-1",
    actionKind: "REVIEW_PAYMENT",
  },
  visibility: { canRead: true, canAct: true },
  updatedAt: new Date("2026-06-26T14:00:00.000Z"),
  rank: {
    priority: "high",
    group: "investigate",
    lens: "attention",
    lane: "critical",
    withinLaneRank: 50,
  },
  workstationCompat: {
    workstationKind: "investigate",
    filterCategory: "payments",
    status: "DUE",
    nextStep: "Record payment or waive requirement.",
    subtitle: "$1,500",
    parentRecordId: "job-1",
    href: "/jobs/job-1",
    valueLabel: "$1,500",
  },
};

export const customerRequestAttentionFixture: OperationalAttentionItem = {
  id: "customer_request:request-1",
  kind: "customer_request",
  severity: "attention",
  ownerRoles: [StaffRole.OWNER, StaffRole.ADMIN, StaffRole.OFFICE],
  sourceType: "CustomerRequest",
  sourceId: "request-1",
  jobId: "job-1",
  customerId: "customer-1",
  title: "Customer asked about schedule",
  reason: "Can we move the appointment to Friday?",
  safeNextAction: {
    label: "Review and resolve the customer portal request.",
    href: "/jobs/job-1#job-customer-portal",
    actionKind: "REVIEW_CUSTOMER_REQUEST",
  },
  visibility: { canRead: true, canAct: true },
  updatedAt: new Date("2026-06-26T13:00:00.000Z"),
  rank: {
    priority: "medium",
    group: "investigate",
    lens: "attention",
    lane: "critical",
    withinLaneRank: 60,
  },
  workstationCompat: {
    workstationKind: "job",
    filterCategory: "jobs",
    status: "NEEDS_REVIEW",
    nextStep: "Review and resolve the customer portal request.",
    subtitle: "Cody Homeowner",
    typeLabel: "Customer request",
    parentRecordId: "job-1",
    href: "/jobs/job-1#job-customer-portal",
  },
};

export const unreadableCommercialAttentionFixture: OperationalAttentionItem = {
  ...quoteActivationAttentionFixture,
  id: "quote_activation:quote-hidden",
  sourceId: "quote-hidden",
  quoteId: "quote-hidden",
  title: "Hidden quote",
  visibility: {
    canRead: false,
    canAct: false,
    reason: "Commercial queue is not visible to this role.",
  },
};

export const redactedCommercialAttentionFixture: OperationalAttentionItem = {
  ...paymentReviewAttentionFixture,
  id: "payment_review:payment-redacted",
  sourceId: "payment-redacted",
  title: "Payment hold",
  reason: "Payment hold - contact office.",
  safeNextAction: {
    label: "Contact office",
    href: "/jobs/job-1",
    actionKind: "CONTACT_OFFICE",
  },
  visibility: {
    canRead: true,
    canAct: false,
    redacted: true,
    reason: "Payment details are hidden for this role.",
  },
  workstationCompat: {
    ...paymentReviewAttentionFixture.workstationCompat!,
    workstationKind: "investigate",
    filterCategory: "payments",
    status: "Payment hold",
    nextStep: "Contact office.",
    subtitle: "Hidden payment details",
    valueLabel: "$9,999",
    paymentHoldLabel: "Deposit - $9,999",
  },
};

export const operationalAttentionFixtures = [
  quoteActivationAttentionFixture,
  changeOrderSendAttentionFixture,
  changeOrderApplyAttentionFixture,
  taskProofAttentionFixture,
  paymentReviewAttentionFixture,
  customerRequestAttentionFixture,
  unreadableCommercialAttentionFixture,
  redactedCommercialAttentionFixture,
] as const;
