import assert from "node:assert/strict";
import test from "node:test";
import type { WorkstationWorkItem } from "@/lib/workstation-query";
import {
  attentionResolverContextFixture,
  changeOrderApplyAttentionFixture,
  customerRequestAttentionFixture,
  operationalAttentionFixtures,
  paymentReviewAttentionFixture,
  quoteActivationAttentionFixture,
  taskProofAttentionFixture,
} from "./test-fixtures";
import { resolveOperationalAttentionItems } from "./resolve-operational-attention-items";
import { mapAttentionItemToWorkstationWorkItem } from "./workstation-mapper";

function pickWorkstationParityFields(item: WorkstationWorkItem) {
  return {
    id: item.id,
    kind: item.kind,
    status: item.status,
    reason: item.reason,
    nextStep: item.nextStep,
    priority: item.priority,
    group: item.group,
    lens: item.lens,
    lane: item.lane,
    withinLaneRank: item.withinLaneRank,
    filterCategory: item.filterCategory,
    recordId: item.recordId,
    parentRecordId: item.parentRecordId,
    href: item.href,
    actionKind: item.actionKind,
    actionLabel: item.actionLabel,
    actionIssueId: item.actionIssueId,
    actionTaskId: item.actionTaskId,
    workflowNextActionType: item.workflow?.nextAction?.type,
    workflowNextActionLabel: item.workflow?.nextAction?.label,
  };
}

test("Slice 1 mapper preserves current Workstation-facing DTO fields for representative scenarios", () => {
  const result = resolveOperationalAttentionItems(attentionResolverContextFixture, {
    items: operationalAttentionFixtures,
  });
  const mapped = result.items
    .map(mapAttentionItemToWorkstationWorkItem)
    .filter((item): item is WorkstationWorkItem => item !== null);

  assert.deepEqual(
    mapped.map((item) => item.id),
    [
      quoteActivationAttentionFixture.id,
      "change_order_send:co-1",
      changeOrderApplyAttentionFixture.id,
      taskProofAttentionFixture.id,
      paymentReviewAttentionFixture.id,
      customerRequestAttentionFixture.id,
      "payment_review:payment-redacted",
    ],
  );

  assert.deepEqual(
    mapped.map(pickWorkstationParityFields),
    [
      {
        id: "quote_activation:quote-1",
        kind: "quote",
        status: "Approved - ready to activate",
        reason: "Approved quote is waiting for job setup.",
        nextStep: "Activate job",
        priority: "critical",
        group: "investigate",
        lens: "attention",
        lane: "critical",
        withinLaneRank: 10,
        filterCategory: "quotes",
        recordId: "quote-1",
        parentRecordId: "customer-1",
        href: "/quotes/quote-1/execution-review",
        actionKind: undefined,
        actionLabel: undefined,
        actionIssueId: undefined,
        actionTaskId: undefined,
        workflowNextActionType: "ACTIVATE_JOB",
        workflowNextActionLabel: "Activate job",
      },
      {
        id: "change_order_send:co-1",
        kind: "change-order",
        status: "Change Order DRAFT",
        reason:
          "This Change Order changes price only. Confirm it does not change the work plan before sending.",
        nextStep: "Mark as price-only",
        priority: "high",
        group: "waiting",
        lens: "waiting",
        lane: "upcoming",
        withinLaneRank: 20,
        filterCategory: "quotes",
        recordId: "co-1",
        parentRecordId: "job-1",
        href: "/jobs/job-1/change-orders?focus=co-1",
        actionKind: undefined,
        actionLabel: undefined,
        actionIssueId: undefined,
        actionTaskId: undefined,
        workflowNextActionType: undefined,
        workflowNextActionLabel: undefined,
      },
      {
        id: "change_order_apply:co-2",
        kind: "change-order",
        status: "Change Order ACCEPTED",
        reason: "Accepted Change Order is waiting to be applied to the job.",
        nextStep: "Apply accepted Change Order.",
        priority: "critical",
        group: "ready",
        lens: "attention",
        lane: "critical",
        withinLaneRank: 30,
        filterCategory: "quotes",
        recordId: "co-2",
        parentRecordId: "job-1",
        href: "/jobs/job-1/change-orders?focus=co-2",
        actionKind: undefined,
        actionLabel: undefined,
        actionIssueId: undefined,
        actionTaskId: undefined,
        workflowNextActionType: undefined,
        workflowNextActionLabel: undefined,
      },
      {
        id: "proof_required:task-1",
        kind: "task",
        status: "Needs proof",
        reason: "Task needs completion proof.",
        nextStep: "Complete the task.",
        priority: "medium",
        group: "active",
        lens: "attention",
        lane: "due",
        withinLaneRank: 40,
        filterCategory: "tasks",
        recordId: "task-1",
        parentRecordId: "job-1",
        href: "/jobs/job-1",
        actionKind: undefined,
        actionLabel: undefined,
        actionIssueId: undefined,
        actionTaskId: undefined,
        workflowNextActionType: undefined,
        workflowNextActionLabel: undefined,
      },
      {
        id: "payment_review:payment-1",
        kind: "investigate",
        status: "DUE",
        reason: "Payment is due.",
        nextStep: "Record payment or waive requirement.",
        priority: "high",
        group: "investigate",
        lens: "attention",
        lane: "critical",
        withinLaneRank: 50,
        filterCategory: "payments",
        recordId: "payment-1",
        parentRecordId: "job-1",
        href: "/jobs/job-1",
        actionKind: undefined,
        actionLabel: undefined,
        actionIssueId: undefined,
        actionTaskId: undefined,
        workflowNextActionType: undefined,
        workflowNextActionLabel: undefined,
      },
      {
        id: "customer_request:request-1",
        kind: "job",
        status: "NEEDS_REVIEW",
        reason: "Can we move the appointment to Friday?",
        nextStep: "Review and resolve the customer portal request.",
        priority: "medium",
        group: "investigate",
        lens: "attention",
        lane: "critical",
        withinLaneRank: 60,
        filterCategory: "jobs",
        recordId: "request-1",
        parentRecordId: "job-1",
        href: "/jobs/job-1#job-customer-portal",
        actionKind: undefined,
        actionLabel: undefined,
        actionIssueId: undefined,
        actionTaskId: undefined,
        workflowNextActionType: undefined,
        workflowNextActionLabel: undefined,
      },
      {
        id: "payment_review:payment-redacted",
        kind: "investigate",
        status: "Payment hold",
        reason: "Payment hold - contact office.",
        nextStep: "Contact office.",
        priority: "high",
        group: "investigate",
        lens: "attention",
        lane: "critical",
        withinLaneRank: 50,
        filterCategory: "payments",
        recordId: "payment-redacted",
        parentRecordId: "job-1",
        href: "/jobs/job-1",
        actionKind: undefined,
        actionLabel: undefined,
        actionIssueId: undefined,
        actionTaskId: undefined,
        workflowNextActionType: undefined,
        workflowNextActionLabel: undefined,
      },
    ],
  );
});
