import type { Prisma } from "@prisma/client";
import { readContact, readRequest } from "@/lib/lead/lead-projection";

/** True when title is the auto-generated "Quote — {name}" (or Instant Quote) pattern. */
export function isAutoGeneratedQuoteTitle(
  title: string,
  customerName?: string | null,
): boolean {
  const trimmed = title.trim();
  if (!trimmed) {
    return true;
  }
  const match = trimmed.match(/^(Instant Quote|Quote)\s*[—–-]\s*(.+)$/i);
  if (!match) {
    return false;
  }
  if (!customerName?.trim()) {
    return true;
  }
  return match[2].trim().toLowerCase() === customerName.trim().toLowerCase();
}

export function resolveJobCustomerName(
  customer?: { displayName: string } | null,
  lead?: { contact?: Prisma.JsonValue | null } | null,
): string | null {
  const fromCustomer = customer?.displayName?.trim();
  if (fromCustomer) {
    return fromCustomer;
  }
  const fromLead = readContact(lead?.contact).name?.trim();
  return fromLead || null;
}

export function resolveJobScopeLabel(params: {
  jobTitle: string;
  customerName?: string | null;
  lead?: {
    contact?: Prisma.JsonValue | null;
    request?: Prisma.JsonValue | null;
  } | null;
}): string | null {
  const { jobTitle, customerName, lead } = params;

  const scope = readRequest(lead?.request).scope?.trim();
  if (scope) {
    return scope;
  }

  const requestType = readRequest(lead?.request).type?.trim();
  if (requestType) {
    return requestType;
  }

  const trimmedTitle = jobTitle.trim();
  if (trimmedTitle && !isAutoGeneratedQuoteTitle(trimmedTitle, customerName)) {
    return trimmedTitle;
  }

  return null;
}

/**
 * Compact who / what / where for list cards.
 * Order: customer · scope · jobsite — each segment appears at most once.
 */
export function buildWorkItemContextLine(parts: {
  customerName?: string | null;
  scopeLabel?: string | null;
  jobsiteLine?: string | null;
}): string {
  const customer = parts.customerName?.trim() || null;
  let scope = parts.scopeLabel?.trim() || null;
  const jobsite = parts.jobsiteLine?.trim() || null;

  if (scope && customer && scope.toLowerCase() === customer.toLowerCase()) {
    scope = null;
  }

  return [customer, scope, jobsite]
    .filter((s): s is string => Boolean(s))
    .join(" · ");
}

export function resolveJobWorkContext(params: {
  jobTitle: string;
  customer?: { displayName: string } | null;
  lead?: {
    contact?: Prisma.JsonValue | null;
    request?: Prisma.JsonValue | null;
  } | null;
  jobsiteLine?: string | null;
}): {
  customerName: string | null;
  scopeLabel: string | null;
  contextLine: string;
  parentLabel: string | null;
} {
  const customerName = resolveJobCustomerName(params.customer, params.lead);
  const scopeLabel = resolveJobScopeLabel({
    jobTitle: params.jobTitle,
    customerName,
    lead: params.lead,
  });
  const contextLine = buildWorkItemContextLine({
    customerName,
    scopeLabel,
    jobsiteLine: params.jobsiteLine,
  });

  return {
    customerName,
    scopeLabel,
    contextLine,
    parentLabel: customerName,
  };
}

/** Subtitle for activity feed rows — job context only, no redundant actor echo. */
export function resolveJobActivitySubtitle(params: {
  jobTitle: string;
  customer?: { displayName: string } | null;
  lead?: {
    contact?: Prisma.JsonValue | null;
    request?: Prisma.JsonValue | null;
  } | null;
  jobsiteLine?: string | null;
  actorName?: string | null;
}): string {
  const { contextLine } = resolveJobWorkContext(params);
  if (contextLine) {
    return contextLine;
  }

  const actor = params.actorName?.trim();
  return actor || "System";
}
