import assert from "node:assert/strict";
import test from "node:test";
import {
  buildWorkItemContextLine,
  isAutoGeneratedQuoteTitle,
  resolveJobScopeLabel,
  resolveJobWorkContext,
} from "./work-item-context";

test("buildWorkItemContextLine: customer · scope · jobsite", () => {
  assert.equal(
    buildWorkItemContextLine({
      customerName: "Cody Barbour",
      scopeLabel: "New Roof",
      jobsiteLine: "401 Royal Tern Dr, Vacaville, CA",
    }),
    "Cody Barbour · New Roof · 401 Royal Tern Dr, Vacaville, CA",
  );
});

test("buildWorkItemContextLine: customer · jobsite when no scope", () => {
  assert.equal(
    buildWorkItemContextLine({
      customerName: "Cody Barbour",
      jobsiteLine: "401 Royal Tern Dr, Vacaville, CA",
    }),
    "Cody Barbour · 401 Royal Tern Dr, Vacaville, CA",
  );
});

test("buildWorkItemContextLine: skips scope when it duplicates customer", () => {
  assert.equal(
    buildWorkItemContextLine({
      customerName: "Cody Barbour",
      scopeLabel: "Cody Barbour",
      jobsiteLine: "401 Royal Tern Dr",
    }),
    "Cody Barbour · 401 Royal Tern Dr",
  );
});

test("isAutoGeneratedQuoteTitle: detects Quote — name pattern", () => {
  assert.equal(isAutoGeneratedQuoteTitle("Quote — Cody Barbour", "Cody Barbour"), true);
  assert.equal(isAutoGeneratedQuoteTitle("Quote — Cody Barbour", "Other Person"), false);
  assert.equal(isAutoGeneratedQuoteTitle("New Roof", "Cody Barbour"), false);
});

test("resolveJobScopeLabel: prefers scope over request type", () => {
  assert.equal(
    resolveJobScopeLabel({
      jobTitle: "Quote — Cody Barbour",
      customerName: "Cody Barbour",
      lead: {
        contact: { name: "Cody Barbour" },
        request: { type: "Estimate / quote", scope: "New Roof" },
      },
    }),
    "New Roof",
  );
});

test("resolveJobScopeLabel: uses request type when no scope", () => {
  assert.equal(
    resolveJobScopeLabel({
      jobTitle: "Quote — Cody Barbour",
      customerName: "Cody Barbour",
      lead: {
        contact: { name: "Cody Barbour" },
        request: { type: "Estimate / quote" },
      },
    }),
    "Estimate / quote",
  );
});

test("resolveJobWorkContext: no redundant auto-generated quote title", () => {
  const result = resolveJobWorkContext({
    jobTitle: "Quote — Cody Barbour",
    customer: { displayName: "Cody Barbour" },
    lead: {
      contact: { name: "Cody Barbour" },
      request: { type: "Estimate / quote" },
    },
    jobsiteLine: "401 Royal Tern Dr, Vacaville, CA 95687, USA",
  });

  assert.equal(
    result.contextLine,
    "Cody Barbour · Estimate / quote · 401 Royal Tern Dr, Vacaville, CA 95687, USA",
  );
  assert.equal(result.parentLabel, "Cody Barbour");
});
